Implementation of oemof constraint method and of saving of results
chrklemm/SESMG pull request #45
Opened 2021-01-06 12:24 UTC by GregorBecker

- Conversions that were necessary to optimise according to two variables (for example emissions and monetary costs). #33 
- Introduction of an automatically created result folder of the format Scenarioname-date--time which can now be selected for re-view in the GUI. #17

2021-01-06 14:45 UTC, chrklemm requested changes
Ein paar kleine Anmerkungen, sonst sieht alles gut aus!

2021-01-06 14:45 UTC, chrklemm commented on SESMG_EXE.py
> +    """ 1. Creates the folder where the results would be saved
"1. Creates the folder where the results **will** be saved"

2021-01-06 14:45 UTC, chrklemm commented on SESMG_EXE.py
> +        raise SystemError('No optimization since the last restart')
'No optimization since the last restart, **please select a result folder!**'

2021-01-08 10:16 UTC, GregorBecker commented on SESMG_EXE.py
> +from datetime import datetime
No, because it is a standard python library.

2021-01-08 10:17 UTC, GregorBecker commented on SESMG_EXE.py
> +    """ 1. Creates the folder where the results would be saved
Done.

2021-01-08 10:17 UTC, GregorBecker commented on SESMG_EXE.py
> +        raise SystemError('No optimization since the last restart')
Done

2021-01-08 10:19 UTC, merged