Thermal development
chrklemm/SESMG pull request #53
Opened 2021-01-29 10:15 UTC by YannickWittor

Implementation of oemof.thermal components

- concentrating solar power, 
- absorption chiller,
- solar thermal collector, 
- compression chiller (addition of heat pump function) and
- stratified thermal storage.

2021-01-29 12:46 UTC, chrklemm commented on program_files/create_objects.py
> +        """
Update to new docstring format (ask @GregorBecker )

2021-01-29 12:46 UTC, chrklemm commented on program_files/create_objects.py
> +
Umrechnung von kW in W im kommentar erwähnen

2021-01-29 12:46 UTC, chrklemm commented on program_files/create_objects.py
> +                            'variable output constraint costs 2/(CU/kWh)'],
kein Leerzeichen vor "/"?

2021-01-29 12:46 UTC, chrklemm commented on program_files/create_objects.py
> +                        'variable output constraint costs 2/(CU/kWh)']
Leerzeichen? s.o.

2021-01-29 12:46 UTC, chrklemm commented on program_files/create_objects.py
> +        """
KOrrektes docstring format?

2021-01-29 12:46 UTC, chrklemm commented on program_files/interim_data/characteristic_parameters.csv
> +Kuehn,5,single-effect absorption chiller,10,2.5,1.8,0.42,0.9,0.51,2,,,
Technical-Data not into the "interim data"-folder!

2021-01-29 14:21 UTC, YannickWittor commented on program_files/create_objects.py
> +                            'variable output constraint costs 2/(CU/kWh)'],
im scenario 0.0.2 sind keine Leerzeichen, im aktuellen scenario im Masterbranch aber schon. Soll ich es ändern für 0.0,2?

2021-02-02 16:04 UTC, chrklemm commented on program_files/create_objects.py
> +                            'variable output constraint costs 2/(CU/kWh)'],
0.0.2 ? meinst du 0.2.0? Das Masterbranch-Szenario sollte korrekt sein.

2021-02-02 16:22 UTC, chrklemm commented on SESMG_EXE.py
> +    """ 1. Creates the folder where the results would be saved
"would" (würden)?? "will" ist denke ich richtig

2021-02-02 16:22 UTC, chrklemm commented on SESMG_EXE.py
> +        raise SystemError('No optimization since the last restart')
Wieso hast du die zweite Zeile mit 'please select a result folder!' gelöscht?

2021-02-02 16:22 UTC, chrklemm commented on SESMG_EXE.py
> -                        + 'r"'+save_path.get()+'"', timeout=10, shell=True)
Ich glaube die ursprüngliche Formatierung ist notwendig. Wieso hast du sie geändert?

2021-02-02 16:22 UTC, chrklemm commented on SESMG_EXE.py
> +scenario_path = StringVar(window, str(os.path.join(os.path.dirname(__file__), 'scenario_v0.2.0.xlsx')))
@GregorBecker, ist dieses update entsprechend unserer Logik v0.2.0 oder v0.1.2?

2021-02-02 16:22 UTC, chrklemm commented on SESMG_EXE.py
> +                               getSavePath, 'Choose', save_path.get()],
Auch diese Änderungen hatte seinen Grund.
Du updatest hier unsere änderungen auf eine ältere Version, welche du in deinem Branch verwendest....das soll so nicht sein.....

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +defined if the parameter "technology" is set on "solar_thermal_flat_plate" or "CSP".The following parameters have to be entered:
Hier stimmt etwas nicht...Zeilen doppelung?

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +- **input**: Has to be set to "electricity_bus", if "technology" is set to "CSP" or "solar_thermal_flat_plate". Otherwise has to be set to "x".
Das stimmt nicht. Der Input kann ein beliebiger Elektrizitäts-Bus sein und muss NICHT ein bestimmter bus sein....Wie der Nutzer seine Busse bezeichnet ist ihm überlassen

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +- **Azimuth (PV ONLY) or (Solar Heat)**: Specifies the orientation of the PV or solar thermal module in degrees. Values between 0 and 360 are permissible (0 = north, 90 = east, 180 = south, 270 = wes
Wieso zwei klammern? Wie wäre es mit "Azimutz (PV and Solar Heat)"? Gilt dann entsprechend auch für alle folgenden einträge

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +- **Azimuth (PV ONLY) or (Solar Heat)**: Specifies the orientation of the PV or solar thermal module in degrees. Values between 0 and 360 are permissible (0 = north, 90 = east, 180 = south, 270 = wes
Hast du geprüft ob in oemof-thermal das gleiche Gradsystem verwändet wird? Teilweise werden diese gradzahlen auch anders verwendet.

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +- **cleanliness (Solar Heat)**: Specifies the cleanliness of a parabolic through collector. Only required if "technology" is set to "CSP".
"Cleanliness" statt "cleanliness". Bitte auf einheitliche schreibweisen achten.

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +- **ETA 0 (Solar Heat)**: Optical efficiency of the collector. Only required if "technology" is "CSP" or "solar_thermal_flate_plate". Specific values can be found in data sheets. The optical efficien
Die Beschreibung, was die größe bedeutet gehört nicht hierhin sondern in das Kapitel "Structure of Energy Systems"

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +**Note: Exemlpary values for CSP technology**
Auch das gehört hier nicht hin.

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
>  .. csv-table:: Exemplary input for the sources sheet
Diese Tabelle muss entsprechend deiner Änderungen angepasst werden

2021-02-02 16:22 UTC, chrklemm commented on docs/getting_started/how_to_use.rst
> +- **heat source (CHT)**: Specifies the heat source. At the moment are "GroundWater", "Ground", "Air" and "Water" possible.
"At the moment" bitte weglassen und satz entsprechend anpassen

2021-02-02 16:22 UTC, chrklemm commented on docs/structure_of_energy_system/structure.rst
> -the heat pump cycle process can be described by the Coefficient of Performance (COP).
"coefficient of performance" => kleingeschrieben

2021-02-02 16:22 UTC, chrklemm commented on docs/structure_of_energy_system/structure.rst
> -The heat pumps are implemnted by using  `"oemof.thermal" <https://github.com/oemof/oemof-thermal>`_ .
"The compression heat transformers are implemnted using"

2021-02-05 17:13 UTC, YannickWittor commented on SESMG_EXE.py
> +                               getSavePath, 'Choose', save_path.get()],
Ich habe diese Änderungen alle rückgängig gemacht. Ich habe keine Idee, wie sich diese im Programm eingeschlichen haben, die .exe Datei habe ich nur angefasst, um die Version 0.2.0 für das Szenario zu ändern, mehr nicht. GitHub hat mich auf diese Änderungen als Merge-Konflikt auch nicht hingewiesen, deswegen habe ich es übersehen.

2021-02-05 17:42 UTC, YannickWittor commented on docs/getting_started/how_to_use.rst
>  .. csv-table:: Exemplary input for the sources sheet
Soll dann hier noch eine Extra-Zeile für solar thermal? Bei den komponenten für PV in den letzten Spalten überall "x". Was denkst du?

2021-02-05 17:47 UTC, YannickWittor commented on docs/getting_started/how_to_use.rst
> +- **Azimuth (PV ONLY) or (Solar Heat)**: Specifies the orientation of the PV or solar thermal module in degrees. Values between 0 and 360 are permissible (0 = north, 90 = east, 180 = south, 270 = wes
in oemof-thermal wird mit 0 bis 360 ° gearbeitet, insofern sollte das passen.

2021-02-05 17:48 UTC, YannickWittor commented on docs/getting_started/how_to_use.rst
> +- **ETA 0 (Solar Heat)**: Optical efficiency of the collector. Only required if "technology" is "CSP" or "solar_thermal_flate_plate". Specific values can be found in data sheets. The optical efficien
Meinst du sowas: "The optical efficiency is a collector specific. Values are based on test methods according to DIN EN ISO 9806."

2021-02-11 09:40 UTC, chrklemm requested changes

2021-02-11 09:40 UTC, chrklemm commented on program_files/create_graph.py
> +                        or i == 'storages' or (i == 'buses' and b['shortage']):
Falls die Spalte 'input' für eine Komponente nicht benötigt wird könnte man diese auch einfach leer lassen. Kannst du das auch berücksichtigen?

2021-02-11 09:40 UTC, chrklemm commented on program_files/create_objects.py
> +        if so['input'] == 'x':
Auch hier könnte der Wert leer sein, s.o.

2021-02-11 09:40 UTC, chrklemm commented on program_files/create_objects.py
> +    def create_source(self, so, timeseries_args, output):
Wieso wurde hier das neue Argument "output" eingeführt? Ist das nicht in "so" angegeben?

2021-02-11 09:40 UTC, chrklemm commented on program_files/create_objects.py
> +        self.create_source(so, {'min': 0, 'max': 1}, self.busd[so['output']])
neues Argument vermutlich doppelung zu "so", s.o.

2021-02-11 09:40 UTC, chrklemm commented on program_files/create_results.py
> +                if comp['input'] == 'x':
s.o.

2021-02-11 09:40 UTC, chrklemm commented on program_files/create_results.py
>                      df_list_of_components = \
Hast du die Ergebnisausgabe deiner Komponenten vollständig und ausführlich geprüft? Wird alles korrekt dargestellt?

2021-02-11 09:40 UTC, chrklemm commented on program_files/technical_data/characteristic_parameters.csv
> +Kuehn,5,single-effect absorption chiller,10,2.5,1.8,0.42,0.9,0.51,2,,,
Ist diese Datei in der doku beschrieben? Könnte man dort problemlos weitere zeilen hinzufügen?

2021-02-11 09:41 UTC, chrklemm commented
Färbst du bitte noch die Spalten, welche sich nur auf die neuen Komponenten beziehen farblich ein? So wird die Tabelle übersichtlicher

2021-02-11 11:21 UTC, GregorBecker requested changes
There are some form and function related things I would change if you have any questions about the notes please feel free to contact me.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +            :type tf: dict
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +    def compression_heat_transformer(self, tf, data):
add type hints

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +                    - 'chiller'
has to be checked s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +                - Standard Input information of transformer class
1493 has to be a blank line

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +                      for possible inputs.
has to be checked s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +            @ Yannick Wittor - yw090223@fh-muenster.de, 07.01.2021
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +    def generic_storage(self, s):
type hint s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
>      def __init__(self, nodes_data, nodes, busd):
type hint s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +    def stratified_thermal_storage(self, s):
type hint s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_objects.py
> +            @ Yannick Wittor - yw090223@fh-muenster.de, 26.01.2021
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                        Electricity Input (Solar Heat only),
has been changed in the documentation branch -> can lead to problems -> has to be checked

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                elif comp['input'] != 'x':
can be else without the if condition

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                    if comp['input'] == 'x':
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                    elif comp['input'] != 'x':
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                if comp['input'] == 'x':
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                if comp['input'] != 'x':
use else s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                    elif index == ((comp['label'] + '_low_temp' + '_bus',
why do you separate the string

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                    elif index == ((comp['label'] + '_high_temp' + '_bus',
why do you separate the string

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                elif comp['mode'] != 'x':
s.o.

2021-02-11 11:21 UTC, GregorBecker commented on program_files/create_results.py
> +                elif comp['mode'] != 'x':
s.o.

2021-02-18 08:02 UTC, YannickWittor commented on SESMG_EXE.py
> +scenario_path = StringVar(window, str(os.path.join(os.path.dirname(__file__), 'scenario_v0.2.0.xlsx')))
nothing, is deleted

2021-02-18 12:58 UTC, YannickWittor commented on docs/getting_started/how_to_use.rst
> +- **ETA 0 (Solar Heat)**: Optical efficiency of the collector. Only required if "technology" is "CSP" or "solar_thermal_flate_plate". Specific values can be found in data sheets. The optical efficien
angepasst

2021-02-18 12:59 UTC, YannickWittor commented on docs/getting_started/how_to_use.rst
> +**Note: Exemlpary values for CSP technology**
angepasst

2021-02-18 12:59 UTC, YannickWittor commented on docs/getting_started/how_to_use.rst
>  .. csv-table:: Exemplary input for the sources sheet
Tabellen und Abbildungen angepasst

2021-02-18 13:01 UTC, YannickWittor commented on docs/structure_of_energy_system/structure.rst
> -the heat pump cycle process can be described by the Coefficient of Performance (COP).
angepasst

2021-02-18 13:02 UTC, YannickWittor commented on docs/structure_of_energy_system/structure.rst
> -The heat pumps are implemnted by using  `"oemof.thermal" <https://github.com/oemof/oemof-thermal>`_ .
angepasst

2021-02-18 13:22 UTC, YannickWittor commented on program_files/create_graph.py
> +                        or i == 'storages' or (i == 'buses' and b['shortage']):
- mit den verschachtelten if-Bedingungen gab es Fehler, die hatte ich aber schon beim coden behoben
- Line 144 -> aktueller Stand mit Checklist (siehe Issues) -> Diskussion am 24.02.
- Line 158: Kommentar angepasst, gilt für absorption & compression

2021-02-18 13:31 UTC, YannickWittor commented on program_files/create_objects.py
> +        if so['input'] != 'x':
angepasst

2021-02-18 13:57 UTC, YannickWittor commented on program_files/create_objects.py
> +    def create_source(self, so, timeseries_args, output):
angepasst

2021-02-18 14:32 UTC, YannickWittor commented on program_files/create_objects.py
> +        self.nodes.append(col_bus)
angepasst

2021-02-18 16:41 UTC, YannickWittor commented on program_files/create_objects.py
> +    def compression_heat_transformer(self, tf, data):
angepasst

2021-02-24 13:51 UTC, chrklemm commented
@YannickWittor I tried executing this branch but the SESMG_Exe isn't executing. Did you use an old version of it? please check and solve this error!

2021-02-24 14:00 UTC, GregorBecker commented on program_files/create_objects.py
> +                                          cleanliness, eta_0, c_1, c_2,
If one download this file from git there is a **blank line** and not cleanliness. @YannickWittor

2021-02-24 14:33 UTC, YannickWittor commented
> 
> 
> @YannickWittor I tried executing this branch but the SESMG_Exe isn't executing. Did you use an old version of it? please check and solve this error!

2021-02-24 14:35 UTC, YannickWittor commented on program_files/create_objects.py
> +                                          cleanliness, eta_0, c_1, c_2,
@chrklemm @GregorBecker 
I uploaded my local changes now. Everything should work, I just did a test run.

2021-02-24 15:00 UTC, YannickWittor commented on program_files/create_results.py
>                      df_list_of_components = \
yes, I checked the components and results for correctness

2021-05-10 18:52 UTC, YannickWittor commented on program_files/create_objects.py
> +                    self.solar_heat_source(so)
done

2021-05-10 18:56 UTC, YannickWittor commented on program_files/create_objects.py
> +                        'variable output constraint costs 2/(CU/kWh)']
done

2021-05-10 18:58 UTC, YannickWittor commented on program_files/create_objects.py
> +    def stratified_thermal_storage(self, s):
s.o.

2021-05-10 19:02 UTC, YannickWittor commented on program_files/create_results.py
> +                elif comp['input'] != 'x':
done

2021-05-10 19:02 UTC, YannickWittor commented on program_files/create_results.py
> +                    if comp['input'] == 'x':
done

2021-05-10 19:02 UTC, YannickWittor commented on program_files/create_results.py
> +                if comp['input'] == 'x':
done

2021-05-10 19:04 UTC, YannickWittor commented on program_files/create_results.py
> +                if comp['input'] != 'x':
done

2021-05-10 19:05 UTC, YannickWittor commented on program_files/create_results.py
> +                    elif index == ((comp['label'] + '_low_temp' + '_bus',
reconnected

2021-05-10 19:05 UTC, YannickWittor commented on program_files/create_results.py
> +                    elif index == ((comp['label'] + '_high_temp' + '_bus',
reconnected

2021-05-10 19:05 UTC, YannickWittor commented on program_files/create_results.py
> +                elif comp['mode'] != 'x':
done

2021-05-10 19:05 UTC, YannickWittor commented on program_files/create_results.py
> +                elif comp['mode'] != 'x':
done

2021-06-23 12:53 UTC, merged